# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - aidefcom

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read       # cần cho actions/checkout
      id-token: write      # cần cho azure/login (OIDC)

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          # Nếu app của bạn set "engines": { "node": "20.x" } thì nên để 20.x
          node-version: '20.x'

      - name: Install, build and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A85F5C24B9144D95A2EE6AAEEBAB9F11 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6475ECA168124326A66B725C209E0DF1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_168DBA1F2160435F8521781FCFAD1618 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'aidefcom'
          slot-name: 'Production'   # nếu bạn không dùng slot riêng có thể bỏ dòng này
          package: .
